name: 'civica_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
seed-paths: ["seeds"]
docs-paths: ["docs"]

target-path: "target"
clean-targets: ["target","dbt_packages"]

# ===== Entornos (DEV/PRO) =====
# DBT_ENVIRONMENTS = PEDROJLM_DEV  |  PEDROJLM_PRO
vars:
  #ENV_PREFIX: "{{ env_var('DBT_ENVIRONMENTS', 'PEDROJLM_DEV') }}"
  #BRONZE_DB: "{{ var('ENV_PREFIX') }}_BRONZE_DB"

  physics:
    model: "gravity"
    G: 1.0
    alpha: 1.0
    beta: 1.0
    gamma: 2.0
    min_dist_km: 0.5

models:
  civica_project:
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
      # Deja el "Custom schema" en dbt Cloud (p.ej. DBT_PEDROJLM) o añade aquí +schema si prefieres gestionarlo en repo

 #   intermediate:
 #     +materialized: view
 #     +database: "{{ env_var('DBT_SILVER_DB', 'PEDROJLM_DEV_SILVER_DB') }}"
 #     +schema: "DBT_PEDROJLM"
 #     +tags: ["intermediate","silver"]
    # marts:
    #   +materialized: table
    #   +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
    #   # +schema: ... (si no usas Custom schema en Cloud)

seeds:
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"
  +schema: "SEEDS"

#snapshots:
#  +transient: false
#  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
#  +target_schema: snapshots